### ISSUE TITLE
unexpected identifier "string"

### ISSUE THREAD

**Issue by mohasin-dev** [sebastianbergmann/version#20]
Parse error: syntax error, unexpected identifier "string", expecting variable in vendor/sebastian/version/src/Version.php on line 25

This issue found while upgrading  Laravel 10x

**Comment by sebastianbergmann** [comment]
This sounds like you are trying to use a current version of this library with a version of PHP that is too old.

**Comment by sebastianbergmann** [comment]
I am sorry, but the problem is on your end. You are likely not using the version of PHP you think you are using.
